accounts/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import signup

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
    path("", RedirectView.as_view(url="/receipts/")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    AccountCreateView,
    ExpenseCategoryListView,
    ExpenseCategoryCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_category"
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category"
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account"
    )
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="categories",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL,
        related_name="accounts",
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        "ExpenseCategory",
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    account = models.ForeignKey(
        "Account",
        related_name="receipts",
        on_delete=models.CASCADE,
        null=True
    )
    context_object_name = "receipt_list"

accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def signup(request):
    # run request (when user makes a request on the signup page)
    if request.method == 'POST':
        # UserCreationForm is automatically generated from import
        form = UserCreationForm(request.POST)
        # if the form inputs are valid
        if form.is_valid():
            # newly create form is saved to user
            user = form.save()
            # login will be passed after request is passed
            # user is the form that was just created and saved
            login(request, user) # this line basically means, log in the user that just made this request and create the account
            # returns the user to the home page
            return redirect('home')
    # if they're just visiting this page, they're just directed to the signup page
    else:
        form = UserCreationForm()

    return render(request, 'registration/signup.html', {'form': form})

receipts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from receipts.models import ExpenseCategory, Receipt, Account
# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_categories/expense_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_categories/expense_create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_category")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/account_create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")

receipts/templates/accounts/account_create.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Create Account</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
              <button>Create</button>
            </div>
        </form>
    </div>
{% endblock content %}

receipts/templates/accounts/account_list.html
{% extends 'base.html' %} 

{% block content %}
<div>
  <h1>Accounts</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for account in account_list %}
      <tr>
        <td>{{ account.name }}</td>
        <td>{{ account.number }}</td>
        <td>{{ account.receipts.all|length }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

receipts/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title></title>
  </head>
  <body>
    <main>
      <header>
        <nav>
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'home' %}">Receipts</a>
          </li>
          <li>
            <a href="{% url 'create_receipt' %}">Create receipt</a>
          </li>
          <li>
            <a href="{% url 'list_accounts' %}">Accounts</a>
          </li>
          <li>
            <a href="{% url 'create_account' %}">Create account</a>
          </li>
          <li>
            <a href="{% url 'list_category' %}">Categories</a>
          </li>
          <li>
            <a href="{% url 'create_category' %}">Create category</a>
          </li>
          <li>
            <a href="{% url 'logout' %}">Logout</a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'signup' %}">Sign Up</a>
          </li>
          <li>
            <a href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
        </nav>
      </header>
      {% block content %}
      {% endblock content %}
    </main>
  </body>
</html>

receipts/templates/expense_categories/expense_create.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
              <button>Create</button>
            </div>
        </form>
    </div>
{% endblock content %}

receipts/templates/expense_categories/expense_list.html
{% extends 'base.html' %} {% block content %}
<div>
  <h1>Expense Categories</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of receipts</th>
      </tr>
    </thead>
    <tbody>
      {% for category in expensecategory_list %}
      <tr>
        <td>{{ category.name }}</td>
        <td>{{ category.receipts.all|length }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

receipts/templates/receipts/create.html
<!DOCTYPE html>
<html>
    <head>
        <title></title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create Receipt</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                      <button>Create</button>
                    </div>
                  </form>
            </div>
        </main>
    </body>
</html>

receipts/templates/receipts/list.html
{% extends 'base.html' %} 

{% block content %}
<h1>My Receipts</h1>
<table>
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Total</th>
      <th>Tax</th>
      <th>Date</th>
      <th>Category</th>
      <th>Account</th>
    </tr>
  </thead>
  <tbody>
    {% for receipt in receipt_list %}
    <tr>
      <td>{{ receipt.vendor }}</td>
      <td>{{ receipt.total }}</td>
      <td>{{ receipt.tax }}</td>
      <td>{{ receipt.date }}</td>
      <td>{{ receipt.category }}</td>
      <td>{{ receipt.account }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}